// Renders README screenshots with real fonts and sample data.
//
//   flutter test tool/screenshots_test.dart --update-goldens
//
// Lives outside test/ on purpose: font rendering differs per OS, so these
// images are regenerated by hand, never compared in CI.
//
// The analyzer only treats test/ as test code, hence the ignore below.
// ignore_for_file: invalid_use_of_visible_for_testing_member
import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:weather_application/core/error/errors.dart';
import 'package:weather_application/core/storage/prefs.dart';
import 'package:weather_application/core/theme/app_theme.dart';
import 'package:weather_application/core/utils/weather_code_mapper.dart';
import 'package:weather_application/features/cities/data/models/city_dto.dart';
import 'package:weather_application/features/cities/domain/entities/city.dart';
import 'package:weather_application/features/cities/presentation/screens/cities_screen.dart';
import 'package:weather_application/features/location/domain/entities/place.dart';
import 'package:weather_application/features/location/presentation/providers/location_provider.dart';
import 'package:weather_application/features/onboarding/presentation/onboarding_screen.dart';
import 'package:weather_application/features/settings/presentation/screens/settings_screen.dart';
import 'package:weather_application/features/weather/domain/entities/weather.dart';
import 'package:weather_application/features/weather/presentation/providers/weather_provider.dart';
import 'package:weather_application/features/weather/presentation/screens/day_detail_screen.dart';
import 'package:weather_application/features/weather/presentation/screens/home_screen.dart';
import 'package:weather_application/l10n/app_localizations.dart';
import 'package:skeletonizer/skeletonizer.dart';

const _hanoi = Place(lat: 21.03, lon: 105.85, name: 'Hà Nội');
const _cities = [
  City(id: 1, name: 'Đà Nẵng', lat: 16.07, lon: 108.22, country: 'Việt Nam'),
  City(
    id: 2,
    name: 'TP. Hồ Chí Minh',
    lat: 10.82,
    lon: 106.63,
    country: 'Việt Nam',
  ),
  City(id: 3, name: 'Đà Lạt', lat: 11.94, lon: 108.44, country: 'Việt Nam'),
];

/// Seven plausible days starting 2026-09-26 10:00, around [base] °C.
Weather _weather(double base, WeatherCondition condition) {
  final start = DateTime(2026, 9, 26);
  final now = DateTime(2026, 9, 26, 10, 15);
  double tempAt(DateTime t, int day) =>
      base - 2 + day % 3 + 4 * math.sin((t.hour - 9) / 24 * 2 * math.pi);
  const days = [
    WeatherCondition.partlyCloudy,
    WeatherCondition.showers,
    WeatherCondition.rain,
    WeatherCondition.overcast,
    WeatherCondition.clear,
    WeatherCondition.thunderstorm,
    WeatherCondition.mainlyClear,
  ];
  final hourly = [
    for (var h = 0; h < 7 * 24; h++)
      HourlyForecast(
        time: start.add(Duration(hours: h)),
        temperature: tempAt(start.add(Duration(hours: h)), h ~/ 24),
        condition: h < 24 ? condition : days[h ~/ 24],
        precipitationProbability: ((math.sin(h / 5) + 1) * 45).round(),
        isDay: h % 24 >= 6 && h % 24 < 18,
        apparentTemperature: tempAt(start.add(Duration(hours: h)), h ~/ 24) + 2,
        precipitation: 0,
        windSpeed: 12,
        uvIndex: h % 24 >= 10 && h % 24 < 15 ? 8 : 2,
        humidity: 65,
      ),
  ];
  return Weather(
    current: CurrentWeather(
      time: now,
      temperature: base,
      apparentTemperature: base + 3,
      humidity: 78,
      dewPoint: base - 6,
      isDay: true,
      condition: condition,
      windSpeed: 12,
      windDirection: 135,
      pressure: 1012,
      uvIndex: 8,
      visibility: 10000,
    ),
    hourly: hourly,
    daily: [
      for (var d = 0; d < 7; d++)
        DailyForecast(
          date: start.add(Duration(days: d)),
          condition: d == 0 ? condition : days[d],
          tempMin: base - 6 + d % 3,
          tempMax: base + 3 - d % 2,
          sunrise: start.add(Duration(days: d, hours: 5, minutes: 41)),
          sunset: start.add(Duration(days: d, hours: 17, minutes: 52)),
          uvIndexMax: 9,
          precipitationProbabilityMax: [10, 80, 70, 20, 0, 60, 5][d],
          windSpeedMax: 18,
          windDirectionDominant: 135,
        ),
    ],
  );
}

/// flutter_test draws text with a box font unless the real fonts are loaded.
Future<void> _loadFonts() async {
  final manifest =
      json.decode(await rootBundle.loadString('FontManifest.json')) as List;
  for (final family in manifest.cast<Map<String, dynamic>>()) {
    final loader = FontLoader(family['family'] as String);
    for (final font in (family['fonts'] as List).cast<Map<String, dynamic>>()) {
      loader.addFont(rootBundle.load(font['asset'] as String));
    }
    await loader.load();
  }
}

Future<void> _shoot(
  WidgetTester tester,
  String name,
  Widget screen, {
  Map<String, Object> prefs = const {},
}) async {
  for (final mode in [ThemeMode.light, ThemeMode.dark]) {
    SharedPreferences.setMockInitialValues({
      PrefKeys.savedCities: jsonEncode([
        for (final c in _cities) CityDto.fromEntity(c),
      ]),
      ...prefs,
    });
    final sp = await SharedPreferences.getInstance();
    await tester.pumpWidget(
      ProviderScope(
        key: UniqueKey(),
        retry: noAutoRetry,
        overrides: [
          sharedPreferencesProvider.overrideWithValue(sp),
          currentPlaceProvider.overrideWith((ref) async => _hanoi),
          weatherProvider(
            _hanoi.lat,
            _hanoi.lon,
          ).overrideWith((ref) async => _weather(31, WeatherCondition.clear)),
          for (final p in [_hanoi, for (final c in _cities) c.place])
            airQualityProvider(p.lat, p.lon).overrideWith(
              (ref) async => const AirQuality(usAqi: 74, pm25: 23, pm10: 31),
            ),
          for (final (i, c) in _cities.indexed)
            weatherProvider(c.lat, c.lon).overrideWith(
              (ref) async => _weather(
                [29.0, 33.0, 19.0][i],
                WeatherCondition.partlyCloudy,
              ),
            ),
        ],
        child: MaterialApp(
          debugShowCheckedModeBanner: false,
          theme: AppTheme.light,
          darkTheme: AppTheme.dark,
          themeMode: mode,
          locale: const Locale('vi'),
          localizationsDelegates: AppLocalizations.localizationsDelegates,
          supportedLocales: AppLocalizations.supportedLocales,
          builder: (_, child) =>
              SkeletonizerConfig(data: AppTheme.skeleton, child: child!),
          home: screen,
        ),
      ),
    );
    // Past the gradient and skeleton cross-fade animations.
    await tester.pump();
    await tester.pump(const Duration(seconds: 1));
    await tester.pump(const Duration(seconds: 1));
    await expectLater(
      find.byType(MaterialApp),
      matchesGoldenFile('../docs/screenshots/${name}_${mode.name}.png'),
    );
  }
}

void main() {
  setUpAll(() async {
    await _loadFonts();
    debugDisableShadows = false;
  });

  testWidgets('screenshots', (tester) async {
    // iPhone 15 logical size at 2x, to keep the PNGs small.
    tester.view.physicalSize = const Size(780, 1688);
    tester.view.devicePixelRatio = 2;
    addTearDown(tester.view.reset);

    await _shoot(tester, 'home', const HomeScreen());
    await _shoot(
      tester,
      'day_detail',
      const DayDetailScreen(initialDay: 0, place: _hanoi),
    );
    await _shoot(tester, 'cities', const CitiesScreen());
    await _shoot(tester, 'settings', const SettingsScreen());
    await _shoot(tester, 'onboarding', const OnboardingScreen());
    debugDisableShadows = true;
  });
}
